export const metadata = {
    title: 'Lamp Light Web Solutions - Contact',
    description: 'Generated by create next app',
};


export default function Contact() {
    return (
        <div>
            <h1>Contact Me</h1>
            <p>This is the contact page.</p>
        </div>
    );
}