import Link from 'next/link';
import { Overpass } from "next/font/google";
import './globals.css';
import CustomNavbar from './components/CustomNavbar';
import CustomFooter from './components/CustomFooter';
import './buttons.css';
import './navbar.css';
import './home.css';
import './blog/blog.css';
import './portfolio/portfolio.css';
import './pricing/pricing.css';
import 'bootstrap/dist/css/bootstrap.min.css';
const overpass = Overpass({ subsets: ["latin"] });

export const metadata = {
  title: 'Lamplight Web Consulting',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={overpass.className}>
        <CustomNavbar />
        <main>{children}</main>
        <CustomFooter />
      </body>
    </html>
  );
}