import Link from 'next/link';
import { Inter } from 'next/font/google';
import './globals.css';
import CustomNavbar from './components/CustomNavbar';
import CustomFooter from './components/CustomFooter';
import './buttons.css';
import './navbar.css';
import './home.css';
import 'bootstrap/dist/css/bootstrap.min.css';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Lamp Light Web Solutions',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CustomNavbar />
        <main>{children}</main>
        <CustomFooter />
      </body>
    </html>
  );
}