import ProjectCarousel from "../components/ProjectCarousel";

export const metadata = {
    title: 'Lamp Light Web Solutions - Portfolio',
    description: 'Generated by create next app',
};


const projects = [
    {
        name: 'Project One',
        date: 'January 2023',
        image: '/images/portfolio/port-1.png', // Ensure these paths are correct
    },
    {
        name: 'Project Two',
        date: 'February 2023',
        image: '/images/landing.jpg', // Ensure these paths are correct
    },
    {
        name: 'Project One',
        date: 'January 2023',
        image: '/images/portfolio/testing.png', // Ensure these paths are correct
    },
    {
        name: 'Project Two',
        date: 'February 2023',
        image: '/images/portfolio/port-1.png', // Ensure these paths are correct
    },
];

export default function Portfolio() {
    return (
        <div className="portfolio-container text-center mt-5">
            <h1 className="section-heading">Our Work</h1>
            <h4 className="section-subheading">See some examples of our work!</h4>
            <ProjectCarousel projects={projects} />
        </div>
    );
}