export const metadata = {
    title: 'Lamp Light Web Solutions - Portfolio',
    description: 'Generated by create next app',
};

export default function Portfolio() {
    return (
        <div>
            <h1>My Portfolio</h1>
            <p>This is the portfolio page.</p>
        </div>
    );
}