export const metadata = {
    title: 'Lamp Light Web Solutions - Our Services',
    description: 'Generated by create next app',
};

export default function Services() {
    return (
        <div>
            <h1>Services</h1>
            <p>This is the services page.</p>
        </div>
    );
}